apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::110377296544:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-5T01W5LWP029
      username: system:node:{{EC2PrivateDNSName}}
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::110377296544:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-02T10:39:24Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1585"
  uid: 29a81833-2ccf-43fd-b47b-8508a28e26c0
